### ISSUE TITLE
Make authors in readme generation dynamic 

### ISSUE THREAD

**Issue by mrmrs** [tachyons-css/tachyons-cli#6]
Right now our names are hardcoded into the readme generation - which makes this a little less useful for outside users. The author section of the readme should be dynamically generated from the package.json authors.

**Comment by filipelinhares** [comment]
Hey @mrmrs I found this package [node-authors](https://github.com/DTrejo/node-authors).
Hope this helps :smile:

**Comment by johnotander** [comment]
Undoubtedly helpful @filipelinhares, thanks!

Dynamic author support added in the latest version.
